name: CI CD Pipleine for frontend application

on:
 workflow_call:
   inputs:
     environment:
        description: 'Deployment environment'
        required: true
        type: string
     frontend_version:
        description: 'Frontend version to deploy'
        required: true
        type: string

jobs:
 build:
  runs-on : ubuntu-latest
  steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    - name: Check Docker installation
      run: |
        docker -v
        status=$?
        if [ $status ne 0 ]; then
        echo "Docker not installed"
        else
        echo "Docker already installed"
        fi
    - name: Build Docker image
      run: |
        docker build -t "myapp" .
        
